name: proteinae-multimer
channels:
  - nvidia
  - pytorch
  - conda-forge
  - pyg
  - bioconda
  - nodefaults
dependencies:
  - conda-forge::biotite=0.41.0
  - python=3.10
  - pip
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - cudatoolkit=11.3
  - torchvision=0.13.1
  - pyg::pyg
  - pyg::pytorch-sparse
  - pyg::pytorch-scatter
  - pyg::pytorch-cluster
  - bioconda::mmseqs2
  - pip:
    - pytorch-lightning==2.1.4
    - torchmetrics==1.5.2
    - transformers=4.48.3 # for ESMFold
    - python-dotenv==1.0.1
    - einops==0.6
    - dm-tree==0.1.8
    - loguru==0.7.2
    - hydra-core==1.3.1
    - numpy==1.23.5
    - scipy==1.9.3
    - pandas==1.5.3
    - biopandas==0.5.1
    - wandb==0.17.0
    - tensorboard==2.20.0
    - wget==3.2
    - tqdm==4.66.4
    - ml-collections==0.1.1
    - jaxtyping==0.3.3
    - cpdb-protein==0.2.0
    - loralib==0.1.2
    - biopython==1.85
    - DockQ
    - matplotlib
